import { ref } from 'vue';

export function closeModal() {
  (document.getElementsByClassName("btn-close")[0] as HTMLButtonElement)?.click()
}

export const view = ref('login');
export const repeatOptions = ref([
  { text: 'einmal', value: 0 },
  { text: 'jeden tag', value: 1 },
  { text: 'alle 7 tage', value: 7 },
  { text: 'alle 14 tage', value: 14 },
  { text: 'einmal im monat', value: 31 },
]);

export const standartShoppingItems = ref([
  'Brot',
  'Milch',
  'Eier',
  'Käse',
  'Wurst',
  'Butter',
  'Müsli',
  'Joghurt',
  'Obst',
  'Gemüse',
  'Fleisch',
  'Fisch',
  'Nudeln',
  'Reis',
  'Kartoffeln',
  'Kaffee',
  'Tee',
  'Kakao',
  'Zucker',
  'Salz',
  'Pfeffer',
  'Öl',
  'Essig',
  'Mehl',
  'Backpulver',
  'Hefe',
  'Tomatenmark',
  'Ketchup',
  'Senf',
  'Mayonnaise',
  'Marmelade',
  'Honig',
  'Nüsse',
  'Schokolade',
  'Kekse',
  'Chips',
  'Süßigkeiten',
  'Klopapier',
  'Taschentücher',
  'Seife',
  'Shampoo',
  'Duschgel',
  'Waschmittel',
  'Spülmittel',
  'Spülmaschinentabs',
  'Putzmittel',
  'Kerzen',
  'Batterien',
  'Glühbirnen',
]);